[databases]
# Format: local_db_name = host=db_service_name port=5432 dbname=real_db_name
codeheist = host=db port=5432 dbname=codeheist

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432
auth_type = plain
auth_file = /etc/pgbouncer/userlist.txt
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 20